version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - fulmenef
  ignore:
  - dependency-name: phpstan/phpstan-symfony
    versions:
    - 0.12.16
    - 0.12.19
    - 0.12.20
    - 0.12.21
    - 0.12.26
    - 0.12.27
  - dependency-name: captainhook/captainhook
    versions:
    - 5.8.0
  - dependency-name: phpstan/phpstan
    versions:
    - 0.12.70
    - 0.12.71
    - 0.12.73
    - 0.12.77
    - 0.12.78
    - 0.12.79
    - 0.12.80
    - 0.12.81
    - 0.12.82
    - 0.12.83
  - dependency-name: symfony/console
    versions:
    - 5.2.2
    - 5.2.3
    - 5.2.4
    - 5.2.5
    - 5.2.6
  - dependency-name: symfony/http-client
    versions:
    - 5.2.2
    - 5.2.4
    - 5.2.6
  - dependency-name: symfony/yaml
    versions:
    - 5.2.2
    - 5.2.3
    - 5.2.4
    - 5.2.5
  - dependency-name: symfony/framework-bundle
    versions:
    - 5.2.2
    - 5.2.3
    - 5.2.4
  - dependency-name: symfony/dotenv
    versions:
    - 5.2.2
    - 5.2.3
    - 5.2.4
  - dependency-name: symfony/process
    versions:
    - 5.2.2
    - 5.2.3
    - 5.2.4
  - dependency-name: nyholm/psr7
    versions:
    - 1.4.0
  - dependency-name: symfony/flex
    versions:
    - 1.12.1
    - 1.12.2
