##################################################
#
# Run static code static analysis on each new branch
#
##################################################

name: Continuous integration

on:
  push:
    branches:
      - '**'
      - '!master'

jobs:
  tests:
    name: Static code analysis
    runs-on: ubuntu-latest
    env:
        PHP_VERSION: 7.4

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP with composer v2
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{env.PHP_VERSION}}
          tools: composer:v2

      - name: Install dependencies
        run: composer install --ignore-platform-reqs --prefer-dist --no-progress --optimize-autoloader --classmap-authoritative

      - name: PHP-CS-Fixer
        run: ./vendor/bin/php-cs-fixer fix --verbose --dry-run

      - name: PHPStan
        run: make phpstan

      - name: Security
        run: make security
