##################################################
#
# Run static code static analysis on each new branch
#
##################################################

name: Continuous integration

on:
  push:
    branches:
      - '**'
      - '!master'

jobs:
  tests:
    name: Static code analysis
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache PHP dependencies
        id: cache-dependencies
        uses: actions/cache@v1
        with:
          path: vendor
          key: ${{ runner.OS }}-build-${{ hashFiles('**/composer.lock') }}

      - name: Install dependencies
        if: steps.cache-dependencies.outputs.cache-hit != 'true'
        run: composer install --ignore-platform-reqs --prefer-dist --no-progress --no-suggest --optimize-autoloader --classmap-authoritative

      - name: PHP-CS-Fixer
        run: ./vendor/bin/php-cs-fixer fix --verbose --dry-run

      - name: PHPStan
        run: make phpstan

      - name: Security
        run: make security