##################################################
#
# Create a new .phar and create a release when a tag is pushed
#
##################################################

name: Release version

on:
  workflow_run:
    workflows: ["Continuous integration"]
    branches: ["master"]
    types:
      - completed

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow

      - name: Rename phar
        run: mv bin/magephi magephi.phar

      - name: Prepare release
        id: prepare_release
        run: |
          changelog=$(git log -1 --pretty=%b)
          changelog=${changelog//$'\n'/'%0A'}
          echo "::set-output name=changelog::$changelog"
          echo "::set-output name=tag::$(git describe --tags --exact-match ${{ github.ref }})"

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          tag_name: ${{ steps.prepare_release.outputs.tag }}
          body: ${{ steps.prepare_release.outputs.changelog }}
          files: |
            magephi.phar
            magephi.phar.asc
