##################################################
#
# Create a new .phar and create a release when a tag is pushed
#
##################################################

name: Release version

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    env:
      PHP_VERSION: 7.4

    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{env.PHP_VERSION}}

      - name: Rename phar
        run: mv bin/magephi magephi.phar

      - name: Prepare release
        id: prepare_release
        run: echo "::set-output name=changelog::$(git log -1 --pretty=%B)"

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          draft: true
          body: ${{ steps.prepare_release.outputs.changelog }}
          files: magephi.phar
