##################################################
#
# Create a new .phar and create a release when a tag is pushed
#
##################################################

name: Release version

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    env:
      PHP_VERSION: 7.4

    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow

      - name: Setup PHP with composer v2
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{env.PHP_VERSION}}
          tools: composer:v2

      - name: Validate composer.json and composer.lock
        run: composer validate

      - name: Install dependencies
        run: composer install --ignore-platform-reqs --prefer-dist --no-progress --no-dev --no-suggest --optimize-autoloader --classmap-authoritative

      - name: Compilation
        run: |
          mkdir ~/.magephi
          composer dump-env prod
          docker run --interactive --volume=$(pwd):/app ajardin/humbug-box compile

      - name: Prepare release
        id: prepare_release
        run: |
          old_tag=$(git tag --sort=-creatordate | head -n 2 | tail -n 1)
          changelog=$(git log $old_tag..${{ github.ref }} --format='* %s (%h)' --no-merges --reverse)
          changelog=${changelog//$'\n'/'%0A'}
          echo "::set-output name=changelog::${changelog}"

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: ${{ steps.prepare_release.outputs.changelog }}
          files: ./build/magephi.phar
